### ISSUE TITLE
Couldn't get controller inputs to register.

### ISSUE THREAD

**Issue by optimumbox** [DSprtn/GTFO_VR_Plugin#1]
Hey, awesome work so far! I was able to get the game into the headset just fine, but the game didn't respond to any inputs from my index controllers. Is there an ini I forgot to peek into and edit?

**Comment by DSprtn** [comment]
I'm assuming you're using Knuckles controllers? 
~~If you're not (or if something went wrong with the input binding files) you need to setup or link the inputs yourself in the binding UI. You can do that in SteamVR home. Just look for settings/controller bindings and lookup GTFO VR in recent applications~~.

If the bindings are correct and input is still not working something went wrong with the mod and I'll need to have a look inside your game log file in AppData/LocalLow/10 Chambers Collective/GTFO/outputlog

The default bindings I created are in GTFO_DATA/Streaming Assets/SteamVR_Standalone/

I'll take a better gander at this when I'm back home ^^

**Comment by DSprtn** [comment]
I managed to fix the SteamVR menu crash. You should be able to setup your inputs in-game if they're not linked automatically, I'm gonna push a new release shortly.

It might also be possible to get input bindings from the workshop since I uploaded them there.

**Comment by DSprtn** [comment]
Please try setting up or downloading an input scheme in the newest release and let me know if it works now!

**Comment by optimumbox** [comment]
Will do. To answer your question from earlier, the steamvr input menu wasn't even accessible before, but hopefully this should fix that. If I don't get to it tonight tonight, I definitely will tomorrow.

**Comment by optimumbox** [comment]
Yep, that worked. I could use the knuckles no problem now. Thank you.
