### ISSUE TITLE
I can't activate the snap turn in Oculus Rift S

### ISSUE THREAD

**Issue by Andromaliox** [DSprtn/GTFO_VR_Plugin#11]
I can't activate the snap turn in Oculus Rift S. 
How do I configure the controls in Steam VR to take effect?

**Comment by DSprtn** [comment]
Follow the video here: https://www.youtube.com/watch?v=sZPK1GfqxBE&feature=youtu.be&t=4m14s

**Comment by Andromaliox** [comment]
Thank you, resolved issue
