### ISSUE TITLE
Can't use ingame terminal.

### ISSUE THREAD

**Issue by Hoshi82** [DSprtn/GTFO_VR_Plugin#12]
I tried as sugguested in the other topic. I restarted steamvr and the game two times always with the same result. I captured the last attemp: https://youtu.be/D9O6RRSUKAc

Also I updated to mod v.5.0.1 and BepInex 5.1.0.0 by first  copying and overwriting the BepInex files and then overwriting the mod files.

**Comment by xaedian** [comment]
I also have the same issue. Installed GTFO VR yesterday with BepInEx 5.1.0.0 and GTFO VR 5.0.1, using SteamVR 1.12.5 with HTC Vive headset and standard wand controllers.

**Comment by DSprtn** [comment]
Could you guys mail over the output_log.txt file from C:\Users\$YourPCNameHere$\AppData\LocalLow\10 Chambers Collective\GTFO\output_log.txt over to gtfovrmod@gmail.com? 

Make sure to play the game with the mod and attempt to use the terminal beforehand.

I can't seem to be able to reproduce the issue so it would be a great help!

**Comment by DSprtn** [comment]
It looks like the newest release of BepInEx breaks the mod. For now, repeat the installation using version v5.0.1! 

I'll update the installation to include this info.

**Comment by DSprtn** [comment]
By the way, due to what was broken, when it's fixed it should improve your in-game performance by roughly 40-50%

**Comment by DSprtn** [comment]
Version .0502 of the VR mod should now work no matter which version of BepInEx you have, though I still recommend getting the newest one.

Terminal should work again and performance should improve greatly.
