### ISSUE TITLE
Ping causes other controls to stop working

### ISSUE THREAD

**Issue by xaedian** [DSprtn/GTFO_VR_Plugin#13]
I'm using SteamVR 1.12.5, BepInEx 5.1.0.0 & GTFO VR 0.5.0.1, have bound all the controls how I would like to play, but regardless of what button I bind Ping to, and what method, when activated it seemingly causes all my other inputs to stop responding. I can still look around in the game, but I can't rotate, interact, move, crouch, attack or anything else, requiring me to quit the game and relaunch to restore functionality.

**Comment by DSprtn** [comment]
I'll look into it!

**Comment by DSprtn** [comment]
Fixed in the next update

**Comment by DSprtn** [comment]
Version 0.502 contains the fix for this.
