### ISSUE TITLE
Oculus Quest - Virtual Desktop - Touch Controllers not usable in game menu

### ISSUE THREAD

**Issue by arczi79** [DSprtn/GTFO_VR_Plugin#16]
Not possible to start game from game menu with Oculus Touch controllers. Working area of Touch Controllers cursor is too small and there is no option to move cursor to/above any button. I have to use mouse to start the game, later (when the 3d view of game is started) I go to Steam controller settings and I am selecting Oculus Touch mapping profile and than I can use Oculus Touch in started game. If Iam killed in game - than again  I can not use Oculus Touch in game menu because cursor can not reach any button.... so only option to start next round is to turn off game and sttart it again... :/

**Comment by DSprtn** [comment]
What in-game resolution do you have set, the one within GTFO's in-game settings? Try setting it to a 16:9 one and see if it fixes it.

If that doesn't work, you can move the cursor with the left thumbstick if you're not aiming at the overlay.

I'll look into why this happens exactly.

**Comment by arczi79** [comment]
I am not sure if it matters but I have that monitor: Dell 24" U2417H ULTRASHARP (16:9) WIDESCREEN INFINITYEDGE 1920 X 1080
When I lunched game I didn't change any settings... but I think I saw somewhere scaling option in Steam VR settings for that game (it was set to 100%) but I think resolution there was not a 1920x1080....   I will check it later on when I will be at home.

**Comment by DSprtn** [comment]
No, I mean the in-game setting. SteamVR res should not matter.

**Comment by arczi79** [comment]
I have resolution 1920x1080 in the game menu. I was able to reach that menu only using mouse. With Touch Controllers cursor was stopping a little below the menu.

**Comment by Hoshi82** [comment]
Same here. Tried the Valve Index Controller and Vive Wands. With both I weren't able to reach the settings in up left corner or the launch button on the bottom. I also tried using thumbstick as in the version before but there the cursor didn't move at all. :( Also have set a 16:9 resolution.

**Comment by DSprtn** [comment]
I'll be unable to work on the mod for some time. If you point the right (or left, if using left handed mode) controller away from the screen and use the thumbstick, it should work as a workaround for now.

I'll look into this as soon as I can.

**Comment by Hoshi82** [comment]
No problem :) Also using mouse on pc will do as a workaround for now. :)

**Comment by Hoshi82** [comment]
Any news about a new version...maybe? :)

**Comment by DSprtn** [comment]
I'm waiting for the developers to release a new update. There's a pretty reasonable chance it will kill modding, but if it won't I'd be able to procure an Oculus Quest and fix this up pretty quickly. I didn't get around to fixing it mostly because I expected the update to come out somewhere in the summer and there would be no point in fixing something that wouldn't work at all within weeks anyway. In hindsight I probably should've updated it anyway.

**Comment by Hoshi82** [comment]
I see. Hope the update won't break modding. My question was regarding to an update in general not specific the Quest. Just don't wanted to open an extra issue thread since my question is no issue. :)

**Comment by DSprtn** [comment]
Welp, it did kill mods. I might look into modding for il2cpp but I wouldn't expect much. I'm estimating it might take weeks of work before I get it working again if I decide to but I'm more leaning towards this project being put on hold indefinitely.
