### ISSUE TITLE
Greetings~

### ISSUE THREAD

**Issue by AlyxiaFox** [DSprtn/GTFO_VR_Plugin#17]
Hello friend!~ I saw GTFO switched over to IL2cpp and was curious if you were going to rewrite or move over to [Melon loader ](https://github.com/HerpDerpinstine/MelonLoader )because of this. 

Thanks for your time and I look forward to future developments~

**Comment by DSprtn** [comment]
I might, if patching support is added. Until then it might be a bit difficult.

**Comment by AlyxiaFox** [comment]
Talked to one of the dev's for Melon Loader, and they are going to work on adding support for GTFO soon. We worked on it for a couple hours last night to get it to load the API and its having issues currently. Ill update you when I know more.

**Comment by Hoshi82** [comment]
Sounds promising. Let's hope they add support again. This vr mod was the whole reason I bought GTFO in the first place.

**Comment by DSprtn** [comment]
I just got a simple mod working with MelonLoader in GTFO with some pointers from their Discord.

I'll keep you guys posted.

**Comment by DSprtn** [comment]
The system is still quite a bit too limited for what the VR mod needs. It might be possible to get it working but it will be extremely hacky, error prone and will be a big regression from the last version. We'll have to wait until il2cpp modding is a bit more complete I think. 

Thankfully every big limitation I came across is being worked on, so it shouldn't take too long.

**Comment by omenyayl** [comment]
What about the latest BepInEx build? It adds support for IL2cpp in one of their [bleeding edge builds](https://builds.bepis.io/projects/bepinex_be). I was able to get BepInEx to load with the current GTFO version.

**Comment by jessidion** [comment]
> What about the latest BepInEx build? It adds support for IL2cpp in one of their [bleeding edge builds](https://builds.bepis.io/projects/bepinex_be). I was able to get BepInEx to load with the current GTFO version.

Hey man which build please? I couldn't get it to work even with the most recent build they had for IL2cpp

**Comment by jessidion** [comment]
Is it #308?

**Comment by omenyayl** [comment]
The IL2Cpp BepInEx itself loads (it generates the modding files when the game loads), however this VR mod itself won't work because it uses the old UnityMono BepInEx. GTFO moved away from mono to IL2Cpp probably for performance reasons. This mod needs to be rewritten to support the IL2Cpp version of BebInEx. It seems like the author is already rewriting the mod to use MelonLoader instead.

**Comment by jessidion** [comment]
Ah okay. I hope it'll be ready soon!

**Comment by DSprtn** [comment]
I have determined that it is not feasible to get the mod working again under il2cpp.

**Comment by jessidion** [comment]
Dammit thanks!

**Comment by Hoshi82** [comment]
Damn you developers! *raises fist* No seriously that's a huge bummer :(. Bought ther game only for this vr mod and then they screwed it up. Lets really hope it will change in the future but I somehow doubt it. :(

**Comment by DSprtn** [comment]
IL2CPP modding has gotten further along and now it is very possible. In fact, I expect to release a working version this weekend! Check out the thread for the rundown of what's been going on [here.](https://github.com/DSprtn/GTFO_VR_Plugin/issues/19)
