### ISSUE TITLE
A little contribution

### ISSUE THREAD

**Issue by MrKerag** [DSprtn/GTFO_VR_Plugin#18]
Hello! I really liked your plugin. Hope you will sort it out soon.
I've made a low-poly model with normal maps of a wristwatch for your mod, I think it suits the environment better. If you are interested I will send the model along with normals to you.
![watch](https://user-images.githubusercontent.com/67553427/98009461-3b605600-1dfe-11eb-9412-b22dd9b30342.jpg)

**Comment by DSprtn** [comment]
That definitely looks a lot better than my programmer art! 

I'll let you know if/when the mod is working again and we can throw this in ^ ^

**Comment by DSprtn** [comment]
The mod is back and this will definitely fit in here ^^

**Comment by MrKerag** [comment]
> The mod is back and this will definitely fit in here ^^

Nice... what format do you need the model in? Fbx? Stl? Or I could send just a raw project for blender and you may export it in whatever format you want

**Comment by DSprtn** [comment]
.blend is fine

**Comment by MrKerag** [comment]
> .blend is fine

https://drive.google.com/file/d/1joUvR2OQqeRePsE0kjtlQRwo1eMHOJ84/view?usp=sharing

Keep me in contact. If you'll need something regarding 3D modelling, I might help you out.

**Comment by DSprtn** [comment]
I looked at implementing it but there's one change that needs to be made before I can use it. 
![image](https://user-images.githubusercontent.com/11588107/115090894-5ccd7e00-9f16-11eb-98d5-75a4aedaaf1c.png)

The strap needs to be rotated 90 degrees to match the current watch and UI layout, this is so it obscures as little horizontal view as possible. The strap should also be a little thinner for the same reasons.

Here's the old watch model for reference:
[GTFO_Watch.zip](https://github.com/DSprtn/GTFO_VR_Plugin/files/6328165/GTFO_Watch.zip)

**Comment by MrKerag** [comment]
> I looked at implementing it but there's one change that needs to be made before I can use it.
> ![image](https://user-images.githubusercontent.com/11588107/115090894-5ccd7e00-9f16-11eb-98d5-75a4aedaaf1c.png)
> 
> The strap needs to be rotated 90 degrees to match the current watch and UI layout, this is so it obscures as little horizontal view as possible. The strap should also be a little thinner for the same reasons.
> 
> Here's the old watch model for reference:
> [GTFO_Watch.zip](https://github.com/DSprtn/GTFO_VR_Plugin/files/6328165/GTFO_Watch.zip)

Bro. You are watching it in Blender... select the entire thing. Press "R"...Press "Z"... mouse click on empty spice in viewport..write down in a field to the left bottom 90...ENTER
If you want to move the model..instead of R...press G...then X, Y or Z
If you want to scale thing..all the same..Select all the stuff.. Press S

**Comment by MrKerag** [comment]
https://drive.google.com/file/d/1joUvR2OQqeRePsE0kjtlQRwo1eMHOJ84/view?usp=sharing
Here is the updated model. Rotated and scaled a bit. Not sure if ideally. Add me on discord or something. So we could get in touch more easilly. MrKerag#3154

Btw... I want to share with you a little bit of my own project I'm making :) Im making something simmiliar to GTFO but more horror oriented and with no weapons. https://youtu.be/jXUuz7KB-Qc

**Comment by DSprtn** [comment]
That project looks really cool! 

I'll hit you up on Discord if I have any trouble with implementing this version of the watch. I'll get through a few other things first though.

**Comment by DSprtn** [comment]
![image](https://user-images.githubusercontent.com/11588107/115126428-37e91180-9fcf-11eb-8c0c-d9b1214ab85f.png)
Lookin' dandy. I'll have to tweak the layout of the UI and maybe the watch a little bit though.

**Comment by DSprtn** [comment]
![image](https://user-images.githubusercontent.com/11588107/115141070-c47ce980-a03a-11eb-9bf3-9398a7e6e053.png)
I think it looks pretty damn good now ^^
Thanks for the adjustments!
