### ISSUE TITLE
World tilt

### ISSUE THREAD

**Issue by formicsapien** [DSprtn/GTFO_VR_Plugin#2]
The world is tilted after I boot into VR.  No idea how it's happening.

EDIT: I'm pretty sure it's affected by if the mouse was moved before VR is booted with F1

**Comment by DSprtn** [comment]
Are you using a oculus headset?

**Comment by DSprtn** [comment]
Nevermind, I could replicate this on a Vive. I'll look into it.

**Comment by DSprtn** [comment]
It's fixed and will be released in the next update

**Comment by formicsapien** [comment]
AWESOME!  It doesn't matter now, but I'm on and Index.  I'll post 'em as I see 'em.
