### ISSUE TITLE
Toggle VR or Add a second spectator camera?

### ISSUE THREAD

**Issue by Levi777L** [DSprtn/GTFO_VR_Plugin#20]
Personally I just want to look around in VR, not really concerned with playing in VR.  So my goals are a little different then most.  In its current state, what methods would work if all I need really want to do is implement my camera controls into any unity game for looking at the art and then toggling it back to flat screen to play until I get to the next area that I want to stare at.  store.steampowered.com/app/602630

**Comment by Levi777L** [comment]
Is this doable?  :)  http://www.mr-worlds.com/2021/04/starting-work-on-my-next-project.html?m=1

**Comment by DSprtn** [comment]
As this is not related to GTFO VR I'll be closing it. For these kinds of questions you can hit me up on Discord or send me an e-mail.

In general, getting a game to render in VR in the first place is the most difficult thing. I haven't looked at all into a toggling option but that might be a little difficult unless you don't mind OpenVR eating up framerate in the background. Look into the SteamVR plugin (and the modified version on my Github) and OpenVR API.
