### ISSUE TITLE
Controller Mouse Issue

### ISSUE THREAD

**Issue by rocketstrong600** [DSprtn/GTFO_VR_Plugin#21]
i am Unable to move the mouse to the extents of the map and menu gui.  the  only way that works is with the stick control not pointing at the ui.

**Comment by zzzpotato** [comment]
I had the same problem. Use one of the community posted controller bindings. The setup video shows how to get to it

**Comment by DSprtn** [comment]
Are you unable to move at all or just to the very edge?

What device do you have and what resolution are you running the game at? (The in-game setting)

**Comment by DSprtn** [comment]
I was able to replicate and fix the issue, since this is an annoying one I have released a hotfix for it immediately. Let me know if it works for you now ^^

**Comment by rocketstrong600** [comment]
ok will try later

**Comment by rocketstrong600** [comment]
it's fixed no issue now with the hotfix
