### ISSUE TITLE
r2modman support with thunderstore

### ISSUE THREAD

**Issue by jacobmix** [DSprtn/GTFO_VR_Plugin#23]
Any plans to add the mod to https://gtfo.thunderstore.io/package/ ? Would make updating, and installing the mod easier.

**Comment by DSprtn** [comment]
For now it's not compatible because I have my own versions of libraries that other mods are using. Once the changes I need are made official I'll give it another look.

**Comment by DSprtn** [comment]
I'll get back to this as soon as Unhollower is updated.
