### ISSUE TITLE
Not working for rundown 6. Any ETA?

### ISSUE THREAD

**Issue by zmifsx** [DSprtn/GTFO_VR_Plugin#28]
Yup I read the readme. Just wondering when will it work. 

Also, I found boot.config.xml in GTFO_Data that has this line that says vr-enabled=0. 

Does this in any way could mean the game is officially getting VR Support?

**Comment by DSprtn** [comment]
No, that's a standard Unity setting. 

The mod is being updated. A lot of stuff has changed though so it might take a bit.

**Comment by DSprtn** [comment]
There is a beta build available for R6 in the Discord. A release should follow after a week of testing or so.
