### ISSUE TITLE
Can mod be configured for left hand players?

### ISSUE THREAD

**Issue by Hoshi82** [DSprtn/GTFO_VR_Plugin#4]
So in the description it says everything can be rebind in steamvr input settings. So when using the Index Controller I am able to swap analogsticks (movement on right controller, turning on left controller), swap buttons like if jumping is on A-right I can remap it to A-left?
Thats for the controller bindings.

The other thing is can you swap weapons to the left hand? Because aiming with left as a lefty would be very helpfull. ;)

**Comment by DSprtn** [comment]
Yes, you can change that in the config. I updated the readme for more clarity. 
Check Usage notes -> Configuration
