### ISSUE TITLE
Opening menu in game causes flickering and stuttering

### ISSUE THREAD

**Issue by Wolfkhan66** [DSprtn/GTFO_VR_Plugin#43]
Playing on a quest 2 using virtual desktop to connect to steam vr.
Had no other issues and menu works fine on startup and loading up a rundown. Once in game however trying to open the in game menu or the steam vr menu causes everything to stutter and flicker until you manage to close them again.

Is there something that needs to be switched off? Otherwise i have no performance issues

**Comment by DSprtn** [comment]
It's a known issue, the current theory is that it is affected by VRAM usage. Reducing texture size in GTFO's options does seem to fix it most of the time.

**Comment by Wolfkhan66** [comment]
Ah okay, i shall try that this evening and report back

**Comment by Wolfkhan66** [comment]
Reducing the texture size did work and prevented the stuttering and flickering.
On another note can you still control the bots?

**Comment by DSprtn** [comment]
Yeah, there is a binding you can configure that opens the bot command menu.

**Comment by Wolfkhan66** [comment]
Any chance that can be added to the left hand radial menu in the future?

**Comment by DSprtn** [comment]
I've got no plans for any features or improvements at this time other than ProtubeVR hardware support.
