### ISSUE TITLE
Controller bindings wont save when i try to modify 

### ISSUE THREAD

**Issue by Dude-Flash** [DSprtn/GTFO_VR_Plugin#6]
So i used your controller configuration and when i modded it ( i'm a lefty ) it wont "save" and reverts back to your configuration. i tried using another binding and tried creating one from scratch and when i select "save" from the "save to your personal bindings" option.... the just stays on screen unless i cancel or back out.  i tried other games and they are working as intended

**Comment by DSprtn** [comment]
The interface is a bit unresponsive sometimes, I've had it happen too and spamming the save button seemed to do the trick. Alternatively, try doing it either in VR if you were doing it on the desktop or vice versa.

**Comment by Dude-Flash** [comment]
Ok thank you - I will give that a try - I was trying it in VR

**Comment by DSprtn** [comment]
Any luck?

**Comment by Dude-Flash** [comment]
I haven't returned to the game yet - not due to lack of interest just been hella busy and working in a new HMD - have you done anything new to the MOD at all? just curious. I have one request if you are taking them?

**Comment by DSprtn** [comment]
I just released new bugfixes and a fix to the rendering system for way smoother gameplay. 

I'm open to suggestions too ^^

**Comment by Dude-Flash** [comment]
ok cool! - so i use a gunstock ( its a new design im currently trying to get to market ) with all my shooters - the way the proximity is currently doesn't work well with it. can you adjust the distance so the controllers don't need to be so close together to activate the "grab" on the fore end of the gun? ultimately id love for it to be a "toggle grip" with a button like in Pavlov or something but i'm sure its a lot of work.

**Comment by DSprtn** [comment]
I can add a new input for a toggle like that. I'll look into it soon.

**Comment by Dude-Flash** [comment]
that would be awesome if you could - thank you for your work, I cant imagine what it takes to get something of this magnitude up and running

**Comment by DSprtn** [comment]
The requested feature is included in the next version which will be coming out shortly. I'm assuming the original issue has been fixed as I've tried to replicate it and couldn't so I'll be closing the ticket.

**Comment by DSprtn** [comment]
Oh yeah, it will also not save if you don't have all required bindings assigned. You can check which ones you're missing in the middle. I also added new vive bindings to the workshop.
