### ISSUE TITLE
Delay in VR

### ISSUE THREAD

**Issue by Applepiee** [DSprtn/GTFO_VR_Plugin#7]
Hi!

I tried out your mod but I noticed a slight delay when looking around, which causes me to get really sick only after 20 seconds. I tried to lower my settings (SSAO off, 1080p resolution, low shadows,..) but it still has this small delay in vision making it unplayable.

Any idea what I'm doing wrong?

Steam Render Resolution @ 90% / 80Hz
NVIDIA 2080Ti
Ryzen 3950x

**Comment by DSprtn** [comment]
What HMD are you using?

**Comment by Applepiee** [comment]
Hello,
I'm using the Valve Index

**Comment by DSprtn** [comment]
I'll look into it, for now try if playing with motion smoothing off makes it better.

**Comment by DSprtn** [comment]
I have confirmed the issue, seems this is a regression from one of the earlier versions. I'll throw up a hotfix in a few hours. The gameplay is much smoother!

**Comment by DSprtn** [comment]
More improvements have been made in the most recent version, be sure to check it out!
