### ISSUE TITLE
Headtracking feels off

### ISSUE THREAD

**Issue by ahmanwoods** [DSprtn/GTFO_VR_Plugin#8]
Not quite sure how to describe the issue (or if this is just a side effect of the mod), but currently headtracking feels closer to playing a game in vorpx rather than a native VR implementation. I've already updated to the version posted today, which definitely helped with the stuttering, but the headtracking still feels "off" to me. It feels kinda like latency? Not really sure.

Using a Valve Index. 

Edit: I remember Revive needing to add some soft of compensation for the Index's canted display, and that had a similar "off" feeling before it was fixed. Not sure if that applies here but I just thought I'd mention it.

**Comment by DSprtn** [comment]
What HMD, PC setup and in-game/SteamVR settings are you running? 

What kind of frametimes are you getting in-game?

**Comment by ahmanwoods** [comment]
Valve index. 9700k @ 5.1GHz/OC'd 2080ti. Pretty much all low in game settings minus textures. CPU culling load @ extreme. 1080p in game res. 80% res in steamvr.

I'm hitting 9-11.5ms frame times so I'm sitting @ 80fps with minimal drops.

**Comment by DSprtn** [comment]
I found what's wrong, looking into a solution!

**Comment by ahmanwoods** [comment]
Awesome. Thank you so much!!

**Comment by DSprtn** [comment]
Should be fixed in the upcoming hotfix!

Please let me know how the game feels in v0.42!

**Comment by ahmanwoods** [comment]
Feels much better now, thanks again for the fix!
