### ISSUE TITLE
Foam launcher using all ammo + getting stuck walking

### ISSUE THREAD

**Issue by ahmanwoods** [DSprtn/GTFO_VR_Plugin#9]
Currently you're unable to "charge" the foam launcher, as using it instantly puts it to full charge & uses all of your ammo.

I'm also experiencing getting stuck walking due to some strange hardware issue w/ my left index controller. When I flick the stick in certain directions, the controller (per the steamVR input test) inputs a slightly opposite direction once its snapped back to center for a few frames (e.g, I flick to -1 to move left, and once the stick resets to center it inputs 0.1 for a few frames). This results in the "0.1" input getting stuck & making me walk, even though the steamVR input test isn't reporting any further input from the controller, I don't experience getting stuck walking in other titles.

Thanks again!

**Comment by ahmanwoods** [comment]
Nevermind, turns out I get the stick issue in some other games. Guess its time to send my controllers back to valve :D

**Comment by DSprtn** [comment]
I'll look into the cfoam launcher ^^

**Comment by DSprtn** [comment]
Fixed, another hotfix coming up.
